apiVersion: v1
kind: PersistentVolume
metadata:
  name: ret2shell-storage-cache-pv2
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ret2shell-storage-cache
  local:
    path: /srv/ret2shell/backend/storage/cache-pv2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ret2shell-node-master

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ret2shell-storage-cache-pv3
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ret2shell-storage-cache
  local:
    path: /srv/ret2shell/backend/storage/cache-pv3
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ret2shell-node-master

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ret2shell-storage-queue-pv2
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ret2shell-storage-queue
  local:
    path: /srv/ret2shell/backend/storage/queue-pv2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ret2shell-node-master

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ret2shell-storage-queue-pv3
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ret2shell-storage-queue
  local:
    path: /srv/ret2shell/backend/storage/queue-pv3
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ret2shell-node-master
