platform:
  exposure:
    type: ingress
  ingress:
    className: nginx
    hosts:
      - host: ctf.example.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: ret2shell-tls
        hosts:
          - ctf.example.com
  config:
    server:
      externalDomain: ctf.example.com
      externalHttps: true

registry:
  externalAccess:
    enabled: true
    serviceType: NodePort
    nodePort: 30310
    host: registry.example.com:30310
    insecure: true
