platform:
  image:
    repository: ghcr.io/ret2shell/ret2shell
  rbac:
    useClusterAdmin: true
  persistence:
    storageClass: ret2shell-storage-platform
    size: 420Gi
  config:
    cluster:
      enabled: true
      nodeSelector: ""
      traffic: ""
      lifecycle: ""
      enableCapture: true

postgresql:
  mode: internal
  persistence:
    storageClass: ret2shell-storage-database
    size: 140Gi
  metrics:
    enabled: false
    serviceMonitor:
      enabled: false

valkey:
  mode: internal
  architecture: standalone
  auth:
    enabled: true
  persistence:
    storageClass: ret2shell-storage-cache
    size: 10Gi
  metrics:
    enabled: false
    serviceMonitor:
      enabled: false

nats:
  mode: internal
  replicaCount: 1
  auth:
    enabled: true
  jetstream:
    maxMemoryStore: 1Gi
  persistence:
    storageClass: ret2shell-storage-queue
    size: 10Gi
  metrics:
    enabled: false
    serviceMonitor:
      enabled: false

registry:
  mode: internal
  replicaCount: 1
  persistence:
    storageClass: ret2shell-storage-registry
    size: 300Gi
  metrics:
    enabled: false
    serviceMonitor:
      enabled: false

victoriaLogs:
  mode: internal
  persistence:
    storageClass: ret2shell-storage-logs
    size: 3Gi
  serviceMonitor:
    enabled: false
