platform:
  exposure:
    type: nodePort
  service:
    nodePort: 30307
  config:
    server:
      externalDomain: 203.0.113.10:30307
      externalHttps: false

registry:
  externalAccess:
    enabled: true
    serviceType: NodePort
    nodePort: 30310
    host: 203.0.113.10:30310
    insecure: true
