//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use chrono::serde::ts_seconds::{deserialize as from_ts, serialize as to_ts};
use chrono::{DateTime, Utc};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use super::{hint, team};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "extra")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub created_at: DateTime<Utc>,
    pub team_id: i64,
    #[sea_orm(column_type = "Text")]
    pub reason: String,
    pub score: i32,
    pub hint_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    // #[sea_orm(
    //     belongs_to = "super::challenge::Entity",
    //     from = "Column::ChallengeId",
    //     to = "super::challenge::Column::Id",
    //     on_update = "Cascade",
    //     on_delete = "Cascade"
    // )]
    // Challenge,
    #[sea_orm(
        belongs_to = "super::hint::Entity",
        from = "Column::HintId",
        to = "super::hint::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Hint,
    #[sea_orm(
        belongs_to = "super::team::Entity",
        from = "Column::TeamId",
        to = "super::team::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Team,
}

impl Related<team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Team.def()
    }
}

impl Related<hint::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Hint.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
