//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use super::challenge;
use chrono::serde::ts_seconds::{deserialize as from_ts, serialize as to_ts};
use chrono::{DateTime, Utc};
use sea_orm::{entity::prelude::*, ActiveValue, IntoActiveModel};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "hint")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub created_at: DateTime<Utc>,
    pub challenge_id: i64,
    #[sea_orm(column_type = "Text")]
    pub content: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::challenge::Entity",
        from = "Column::ChallengeId",
        to = "super::challenge::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Challenge,
    #[sea_orm(has_many = "super::extra::Entity")]
    Extra,
}

impl Related<super::challenge::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Challenge.def()
    }
}

impl Related<super::extra::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Extra.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn create_hint(conn: &DatabaseConnection, hint: Model) -> Result<(), DbErr> {
    match challenge::Entity::find_by_id(hint.challenge_id)
        .one(conn)
        .await
    {
        Ok(Some(_)) => {
            let active_model = ActiveModel {
                id: ActiveValue::NotSet,
                ..hint.into_active_model().reset_all()
            };
            active_model.insert(conn).await.map(|_| ())
        }
        Ok(None) => Err(DbErr::RecordNotFound("challenge".to_string())),
        Err(err) => Err(err),
    }
}

pub async fn delete_hint(conn: &DatabaseConnection, id: i64) -> Result<(), DbErr> {
    let hint = Entity::find_by_id(id).one(conn).await?;
    match hint {
        Some(hint) => hint.delete(conn).await.map(|_| ()),
        None => Err(DbErr::RecordNotFound("hint".to_string())),
    }
}

pub async fn get_hint_list(
    conn: &DatabaseConnection,
    challenge_id: i64,
) -> Result<Vec<Model>, DbErr> {
    let hints = Entity::find()
        .filter(Column::ChallengeId.eq(challenge_id))
        .all(conn)
        .await?;
    Ok(hints)
}
