//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::{entity::prelude::*, ActiveValue, IntoActiveModel};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "media")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    #[sea_orm(unique)]
    pub hash: String,
    pub uploader_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UploaderId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn create_media(conn: &DatabaseConnection, media: Model) -> Result<Model, DbErr> {
    let hash = media.hash.clone();
    let active_model = ActiveModel {
        id: ActiveValue::NotSet,
        ..media.into_active_model().reset_all()
    };
    if let Some(model) = Entity::find()
        .filter(Column::Hash.eq(hash.clone()))
        .one(conn)
        .await?
    {
        return Ok(model);
    }
    active_model.insert(conn).await
}
