//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub mod prelude;

pub mod action;
pub mod announcement;
pub mod answer;
pub mod challenge;
pub mod game;
pub mod hint;
pub mod instance;
pub mod institute;
pub mod ip_address;
pub mod media;
pub mod notification;
pub mod platform_info;
pub mod submission;
pub mod tag;
pub mod team;
pub mod user;
pub mod user2_ip_address;
pub mod user2_team;
pub mod write_up;
