//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::action::Entity as Action;
pub use super::announcement::Entity as Announcement;
pub use super::answer::Entity as Answer;
pub use super::challenge::Entity as Challenge;
pub use super::game::Entity as Game;
pub use super::hint::Entity as Hint;
pub use super::instance::Entity as Instance;
pub use super::institute::Entity as Institute;
pub use super::ip_address::Entity as IpAddress;
pub use super::media::Entity as Media;
pub use super::notification::Entity as Notification;
pub use super::platform_info::Entity as PlatformInfo;
pub use super::submission::Entity as Submission;
pub use super::tag::Entity as Tag;
pub use super::team::Entity as Team;
pub use super::user::Entity as User;
pub use super::user2_ip_address::Entity as User2IpAddress;
pub use super::user2_team::Entity as User2Team;
pub use super::write_up::Entity as WriteUp;
