[auditor]
sensitive_word_list = './config/sensitive_word_list.txt'

[auth]
signing_key = 'K3yInD3v3l0pm3nt'
buffer_time = 21600
expires_time = 86400

[auth.oauth_keys]
#xdu_cas = { id = "https://ctf.xidian.edu.cn/account/oauth", key = "NOTNEEDED" }

[bucket]
path = './data/bucket'

[cache]
# Cluster supports here.
# redis://username:password@foo.com:6379/1
# rediss://username:password@foo.com:6379/1
# redis-cluster://username:password@foo.com:30001?node=bar.com:30002&node=baz.com:30003
# redis-sentinel://username:password@foo.com:6379/1?sentinelServiceName=fakename&node=foo.com:30001&node=bar.com:30002
url = 'redis://localhost:6379'

[captcha]
enabled = true
difficulty = 4
validator = 'pow'

[cluster]
enabled = true
try_default = false
auto_infer = true
kube_config_path = "~/.kube/config"
challenge_node_selector = "challenge"          # default node selector for challenges, could be specified in each game.
proxy_image = "ret2shell/container-proxy:main"
traffic = "wsrx"                               # wsrx | plain, default traffic, could be specified in each game.
enable_capture = true
capture_directory = "./data/captures"
cleanup_interval = 60                          # in seconds

[cluster.registry]
external = "ctf.xidian.edu.cn"
server = "ctf.xidian.edu.cn"
insecure = false
#username =
#password =

[database]
db = 'ret2shell'
host = '127.0.0.1'
port = 5432
user = 'ret2shell'
password = 'P@ssw02dInD3v3l0pm3nt'
ssl_mode = 'disable'               # disable, allow, prefer, require, verify-ca, verify-full

[email]
enabled = false
host = 'smtp.example.com'
port = 587
sender = 'Ret2Shell'
username = 'dev@ret.sh.cn'
password = 'P@ssw0rdInD3v3l0pm3nt'
tls = 'starttls'                   #  'none' | 'tls' | 'starttls'

[logging]
directory = './data/log'
level = 'info,tower_http=info,sqlx=warn'
files_kept = 3
compress = true

[media]
path = './data/media'
anti_theft = true
limit = 50            # one user could upload per week

[queue]
host = '127.0.0.1'
port = 4222
### token has higher priority than user & password, only one auth method will be used.
#token = 'T0k3nInD3v3l0pm3nt'
### user and password must be both valid, whether it will be ignored.
#user = 'ret2shell'
#password = 'P@ssw0rdInD3v3l0pm3nt'
#ping_interval = 5
#tls = false

[server]
host = '127.0.0.1'
port = 8080
external_domain = 'dev.ret.sh.cn'
external_https = true
api_base_path = '/api'
cors_origins = '*'
api_rate_limit = 10               # in 5 seconds

### the Following settings could be changed at web admin panel.
### configuration in database will overwrite the following settings.
# name = 'Ret2Shell'
# footer_info = 'Ret 2 Shell'
# footer_url = 'https://github.com/ret2shell/ret2shell'
# subject_info = 'Fight for all the beauty in the world.'
# subject_url = 'https://ret.sh.cn/'
# record = '豫ICP备xxxxxxxx号-1'   # China ICP record
# hide_maker = false

[server.frontend]
serve_type = 'static'    # static | proxy
path = './frontend/dist'
